kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: scaling
  labels:
    app.kubernetes.io/instance: scaling

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: scaling

  minReplicas: 1
  maxReplicas: 10

  targetCPUUtilizationPercentage: 10
