kind: Service
apiVersion: v1

metadata:
  name: scaling
  labels:
    app.kubernetes.io/instance: scaling

spec:
  selector:
    app.kubernetes.io/instance: scaling

  ports:
    - name: http
      port: 80
      targetPort: http
