kind: Deployment
apiVersion: apps/v1

metadata:
  name: web
  labels:
    app.kubernetes.io/instance: web

spec:
  replicas: 1
  revisionHistoryLimit: 2

  strategy:
    rollingUpdate:
      maxUnavailable: 1

  selector:
    matchLabels:
      app.kubernetes.io/instance: web

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: web

    spec:
      containers:
        - name: default
          image: nginx
          ports:
            - name: http
              containerPort: 80
