kind: Service
apiVersion: v1

metadata:
  name: web
  labels:
    app.kubernetes.io/instance: web

spec:
  type: NodePort

  selector:
    app.kubernetes.io/instance: web

  ports:
    - name: http
      port: 80
      targetPort: http
